### ISSUE TITLE
Hang after calling 'connection.start().get()' on Android.

### ISSUE THREAD

**Issue by RVoiseyFirstApp** [SignalR/java-client#63]
I'm attempting to run the following code on an Android client using the head revision of the repo:

```
...
// Change to the IP address and matching port of your SignalR server.
connection = new HubConnection("http://fa-signalr-demo.azurewebsites.net/", "", true, logger);
hub = connection.createHubProxy("chatHub");
...

// This code is an async task so that it wouldn't hang the main thread when debugging.
SignalRFuture<Void> awaitConnection = connection.start();
try {
    awaitConnection.get();
}
catch (InterruptedException e) {
    e.printStackTrace();
} catch (ExecutionException e) {
    e.printStackTrace();
}
...
```

However the get() function never returns and no connection seems to get established. If I attempt to do anything with the connection object after this point, an exception is thrown as it is in a 'Connecting' state but it never moves from this state.

Befire hanging the last log ouput is:

`01-27 21:03:22.512: I/SignalR(13738): HubConnection - Getting connection data: [{"name":"chathub"}]`

This is occuring on multiple devices: a Samsung Galaxy S4 with Android 4.4.2 and a Motorola X wtih Android 4.4.4, are the devices I'm using most often.

Has anyone run in a similar problem or can offer any advice?

Thanks

Full Log:

```
01-27 21:03:19.039: W/ActivityThread(13738): Application com.example.signalrchat is waiting for the debugger on port 8100...
01-27 21:03:19.049: I/System.out(13738): Sending WAIT chunk
01-27 21:03:19.049: I/dalvikvm(13738): Debugger is active
01-27 21:03:19.249: I/System.out(13738): Debugger has connected
01-27 21:03:19.249: I/System.out(13738): waiting for debugger to settle...
01-27 21:03:19.449: I/System.out(13738): waiting for debugger to settle...
01-27 21:03:19.649: I/System.out(13738): waiting for debugger to settle...
01-27 21:03:19.850: I/System.out(13738): waiting for debugger to settle...
01-27 21:03:20.050: I/System.out(13738): waiting for debugger to settle...
01-27 21:03:20.250: I/System.out(13738): waiting for debugger to settle...
01-27 21:03:20.450: I/System.out(13738): waiting for debugger to settle...
01-27 21:03:20.660: I/System.out(13738): debugger has settled (1449)
01-27 21:03:20.690: W/ApplicationPackageManager(13738): getCSCPackageItemText()
01-27 21:03:20.690: I/PersonaManager(13738): getPersonaService() name persona_policy
01-27 21:03:20.861: I/SignalR(13738): HubConnection - Creating hub proxy: chathub
01-27 21:03:20.881: I/SignalR(13738): HubProxy chatHub - Subscribe to event broadcastMessage
01-27 21:03:20.881: I/SignalR(13738): HubProxy chatHub - Creating new subscription for: broadcastmessage
01-27 21:03:20.941: I/SignalR(13738): HubConnection - Entered startLock in start
01-27 21:03:20.941: I/SignalR(13738): State Changed- Connecting
01-27 21:03:20.951: I/SignalR(13738): HubConnection - Start the connection, using AutomaticTransport transport
01-27 21:03:20.951: I/SignalR(13738): HubConnection - Start negotiation
01-27 21:03:20.951: I/SignalR(13738): AutomaticTransport - Start the negotiation with the server
01-27 21:03:21.061: I/Adreno-EGL(13738): <qeglDrvAPI_eglInitialize:381>: EGL 1.4 QUALCOMM build:  (CL3869936)
01-27 21:03:21.061: I/Adreno-EGL(13738): OpenGL ES Shader Compiler Version: 17.01.11.SPL
01-27 21:03:21.061: I/Adreno-EGL(13738): Build Date: 01/17/14 Fri
01-27 21:03:21.061: I/Adreno-EGL(13738): Local Branch: 
01-27 21:03:21.061: I/Adreno-EGL(13738): Remote Branch: 
01-27 21:03:21.061: I/Adreno-EGL(13738): Local Patches: 
01-27 21:03:21.061: I/Adreno-EGL(13738): Reconstruct Branch: 
01-27 21:03:21.071: I/SignalR(13738): HubConnection - Getting connection data: [{"name":"chathub"}]
01-27 21:03:21.081: I/SignalR(13738): HubConnection - Getting connection data: [{"name":"chathub"}]
01-27 21:03:21.081: I/SignalR(13738): AutomaticTransport - Execute the request
01-27 21:03:21.081: I/SignalR(13738): Create new thread for HTTP Connection
01-27 21:03:21.091: I/SignalR(13738): Execute the HTTP Request
01-27 21:03:21.091: I/SignalR(13738): URL: http://fa-signalr-demo.azurewebsites.net/signalr/negotiate?clientProtocol=1.3&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&
01-27 21:03:21.091: I/SignalR(13738): VERB: GET
01-27 21:03:21.091: I/SignalR(13738): Header User-Agent: SignalR (lang=Java; os=android; version=2.0)
01-27 21:03:21.091: I/SignalR(13738): CONTENT: null
01-27 21:03:21.101: D/OpenGLRenderer(13738): Enabling debug mode 0
01-27 21:03:21.281: V/RenderScript(13738): 0x7949c7b0 Launching thread(s), CPUs 4
01-27 21:03:22.232: I/SignalR(13738): Request executed
01-27 21:03:22.492: I/SignalR(13738): AutomaticTransport - Response received
01-27 21:03:22.492: I/SignalR(13738): AutomaticTransport - Read response data to the end
01-27 21:03:22.492: I/SignalR(13738): AutomaticTransport - Trigger onSuccess with negotiation data: {"Url":"/signalr","ConnectionToken":"9GTf9SuWo5p3VFOU2Rb1ohoVEclbIlQtsFj/mgCzmd2Dr1Zx7GVUi+TSRodi83lsEt9HUe9d2rz9oLPNXT7IKKd7valdgmXY0AoPifyalxcErRCTJtYOyxi/3mgM5IqO","ConnectionId":"25d6320a-5db4-4148-8ac6-a421c5d8ae4f","KeepAliveTimeout":20.0,"DisconnectTimeout":30.0,"ConnectionTimeout":110.0,"TryWebSockets":true,"ProtocolVersion":"1.3","TransportConnectTimeout":5.0,"LongPollDelay":0.0}
01-27 21:03:22.502: I/SignalR(13738): HubConnection - Negotiation completed
01-27 21:03:22.502: I/SignalR(13738): HubConnection - ConnectionId: 25d6320a-5db4-4148-8ac6-a421c5d8ae4f
01-27 21:03:22.502: I/SignalR(13738): HubConnection - ConnectionToken: 9GTf9SuWo5p3VFOU2Rb1ohoVEclbIlQtsFj/mgCzmd2Dr1Zx7GVUi+TSRodi83lsEt9HUe9d2rz9oLPNXT7IKKd7valdgmXY0AoPifyalxcErRCTJtYOyxi/3mgM5IqO
01-27 21:03:22.512: I/SignalR(13738): HubConnection - Keep alive timeout: 20.0
01-27 21:03:22.512: I/SignalR(13738): HubConnection - Entered startLock in startTransport
01-27 21:03:22.512: I/SignalR(13738): HubConnection - Starting the transport
01-27 21:03:22.512: I/SignalR(13738): HubConnection - Starting transport for InitialConnection
01-27 21:03:22.512: I/SignalR(13738): HubConnection - Getting connection data: [{"name":"chathub"}]
01-27 21:03:22.512: I/SignalR(13738): HubConnection - Getting connection data: [{"name":"chathub"}]
```

**Comment by gouravd** [comment]
I faced similar issue. In my case the culprit was socket proticol, which is the default in the head rebision. Currently I m using server sent events/long polling as work around.

**Comment by RVoiseyFirstApp** [comment]
You're right; I've changed it to use ServerSentEvents by default and it is working as expected. Shame WebSockets doesn't seem to work.

Thanks!

**Comment by gouravd** [comment]
Can you create a self contained example out of your project that we can use as repro. I would be interested in opening an issue for websockets not working because it seems to work for most.

**Comment by geekcubed** [comment]
Related to #43 ?

**Comment by gouravd** [comment]
Seems distantly related!

**Comment by mattpminer** [comment]
I second this. The call to "awaitConnection.get();" just hangs forever. I've verified it working as expected in a .NET client with nearly the exact same info.

                Log.d(TAG, "starting connection...");
                HubConnection connection = new HubConnection("http://ec2-54-144-98-169.compute-1.amazonaws.com/");
                Log.d(TAG, "creating proxy...");
                HubProxy proxy = connection.createHubProxy("eventHub");
                proxy.subscribe("updateEventInfo").addReceivedHandler(new Action<JsonElement[]>() {
                    @Override
                    public void run(JsonElement[] jsonElements) throws Exception {
                        Log.d(TAG, "JsonElements received");
                    }
                });

                try {
                    Log.d(TAG, "connection.start()...");
                    SignalRFuture<Void> awaitConnection = connection.start();
                    Log.d(TAG, "started");
                    awaitConnection.get();
                    Log.d(TAG, "got");
                } catch (InterruptedException e) {
                    Log.e(TAG,"InterruptedException");
                    e.printStackTrace();
                } catch (ExecutionException e) {
                    Log.e(TAG, "ExecutionException");
                    e.printStackTrace();
                }

**Comment by mattpminer** [comment]
I'm fairly new to using this project but I found the culprit. In signalr-client-sdk\src\main\java\microsoft\aspnet\signalr\client\transport\WebsocketTransport.java changing

        URI uri;
        try {
            uri = new URI(url);
        } catch (URISyntaxException e) {
            e.printStackTrace();
            mConnectionFuture.triggerError(e);
            return mConnectionFuture;
        }

to:

        URI uri;
        try {
            uri = new URI(url.replace("http://", "ws://"));
        } catch (URISyntaxException e) {
            e.printStackTrace();
            mConnectionFuture.triggerError(e);
            return mConnectionFuture;
        }

did the trick. Looks like it was trying to make the web sockets connection over using the http scheme.

**Comment by gouravd** [comment]
oh yeah, you just nailed it Matt. Awesome!

**Comment by gouravd** [comment]
how about a pull request for the same?

**Comment by gouravd** [comment]
Unfortunately it does not help me :(

**Comment by RVoiseyFirstApp** [comment]
Aye tried the same, exactly as @mattpminer described and unfortunately did not work.

**Comment by mattpminer** [comment]
@RVoiseyFirstApp @gouravd Apologies, there was another error that seemed to make the .get() call to hang. I also changed my above client subscription code to use Object instead of JsonElement[]: 

    HubConnection connection = new HubConnection("http://ec2-54-144-98-169.compute-1.amazonaws.com/", "", true, new NullLogger());

    HubProxy proxy = connection.createHubProxy("eventHub");

    proxy.on("updateEventInfo", new SubscriptionHandler1<Object>() {

        @Override
        public void run(final Object val) {
            MainActivity.this.runOnUiThread(new Runnable() {
                public void run() {
                    LinkedTreeMap<String,String> result = (LinkedTreeMap<String,String>) val;
                    txtLine1.setText(result.get("Title"));
                    txtLine2.setText(result.get("Artist"));
                }
            });
        }
    }, Object.class);

    try {
        connection.start().get();
    } catch (InterruptedException e) {
        e.printStackTrace();
    } catch (ExecutionException e) {
        e.printStackTrace();
    }

**Comment by gouravd** [comment]
hmm..In my case, I am the issue occurs even if I do not subscribe to any client callback function

**Comment by e82eric** [comment]
uri = new URI(url.replace("http://", "ws://"));  worked for me.
uri = new URI(url.replace("https://", "wss://"));  didn't work.
is there anything special that needs to be done for ssl?

**Comment by gouravd** [comment]
wss works from browser (Javascript client) atleast for me, but not through this Java-Client

**Comment by e82eric** [comment]
wss worked for me from the browser and the .net sdk.  Any idea if there is a way to trace the wss traffic?

**Comment by gouravd** [comment]
I am also slightly confused in the following part. 

From WebsocketTransport.java, Line 71

url = connection.getUrl() + "signalr/" + connectionString + '?'

In my case when I start a serversentevents/longpolling connection, the connection url that I provide is 
"https://www.mydomain.com/signalr", 
otherwise the connection fails.

If I provide this same connection string for WebSocket, wouldn't the final connection url become

https://www.mydomain.com/signalr/signalr"  ?

If I provide just https://www.mydomain.com/, then I get Negotiation failed error message in the Hub logger.

**Comment by e82eric** [comment]
I added a breakpoint and it does change the url to /signalr/signalr/connect,  which is different that what I see in chrome developer tools using the javascript client which was just signalr/connect.  Unfortunately removing the extra signalr didn't help.  It is sort of weird why ws:// worked with the extra signalr.

**Comment by gouravd** [comment]
I believe the problem with that part of WebsocketTransport.java code is that it assumes everyone creates a HubConnection with useDefaultUrl as true and hence appends "signalr/"

Coming back to the problem in focus, it looks like the problem is socket connection over https secure connection.

**Comment by e82eric** [comment]
it looks like the socket needs to be set up for ssl.  Added this to the WebSocketTransport and it worked.

		SSLContext sslContext = null;
		try {
			sslContext = SSLContext.getInstance( "TLS" );
			try {
				sslContext.init(null, null, null);
			} catch (KeyManagementException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		} catch (NoSuchAlgorithmException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		SSLSocketFactory factory = sslContext.getSocketFactory();// (SSLSocketFactory) SSLSocketFactory.getDefault();
        
        try {
			mWebSocketClient.setSocket(factory.createSocket());
		} catch (IOException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
        
        mWebSocketClient.connect();

**Comment by gouravd** [comment]
@e82eric Is wss protocol still required or does it work with https

**Comment by e82eric** [comment]
It looks like it only works with the wss

**Comment by gouravd** [comment]
@e82eric yes I am using Android

**Comment by e82eric** [comment]
is it a self signed certificate?

**Comment by gouravd** [comment]
No, its a CA signed certificate. I do not think it has anything to do with certificates because Javascript client works fine

**Comment by e82eric** [comment]
what version of android is it?  It looks like there might be problems depending on the version.
https://github.com/TooTallNate/Java-WebSocket/issues/263
Are you running it in the emulator?

**Comment by gouravd** [comment]
I am running on actual phones. I tried both on 5.0.2 (API 21) and 4.4.4 (API 19), but the behavior remains same.

**Comment by gouravd** [comment]
Under WSS support for android at https://github.com/TooTallNate/Java-WebSocket, a link is provided on how to have android work with certificates - http://blog.antoine.li/2010/10/22/android-trusting-ssl-certificates/

Will try this and let know if this helps.

**Comment by EMIN3M1986** [comment]
The websocket problem solved but I have a new problem.
Connection handling dose not work well. Even after I disconnect the internet the connection state is still  reconnecting and close handling does not fire.

**Comment by gouravd** [comment]
@EMIN3M1986 Could you please share how you resolved the websocket problem?

**Comment by EMIN3M1986** [comment]
Yes . I just replaced Http with ws .

**Comment by arnoldpistorius** [comment]
@EMIN3M1986 This seems the same issue as I've reported here https://github.com/SignalR/java-client/issues/54 . It is rather annoying, but a workaround could be a serverside method CloseConnection and let the server close the connection instead of the client.

**Comment by javadjj** [comment]
I write a project that had a 3 part:
1-Windows Client with XP,Seven,8 C#
2-Server With MVC5
3-Android client with JAVA

i finish this project and use from signalR for online communication between three section and almost conflict with all this problems
1-in android hang app when connect to server , Your Server should be Server 2012 and IIS 8 or LocalHost on IIS Xpress on windows 8 with .net framework 4.5 after install server 2012 you must enable WebSockets from Server manager - > add role and feature -> web server >application developmnet - > install WebSockets 
one of my problems was this and solved by enable feature
you can put log in server and see whitch client connect to server
now all my project work right

**Comment by tmedanovic** [comment]
Replacing http:// with ws:// didn't help me either.

It hangs here mResultSemaphore.tryAcquire:

```java
public class SignalRFuture<V> implements Future<V> {
..
@Override
    public V get(long timeout, TimeUnit unit) throws InterruptedException, ExecutionException, TimeoutException {
        if (mResultSemaphore.tryAcquire(timeout, unit)) {
```
Seems related to: https://github.com/SignalR/java-client/issues/28

Has anyone found a working solution for this?

**Comment by tmedanovic** [comment]
I think it hangs because this WebSocketClient onOpen is never called and result is never set so mResultSemaphore.tryAcquire doesn't have anything to acquire and then hangs:

```java
public class WebsocketTransport extends HttpClientTransport {
...
  mWebSocketClient = new WebSocketClient(uri) {
            @Override
            public void onOpen(ServerHandshake serverHandshake) {
                mConnectionFuture.setResult(null);
            }
```
I tried compiling SignalR with https://github.com/TooTallNate/Java-WebSocket which I compiled from source but nothing changed, it still hangs.

**Comment by pranavmehta** [comment]
@tmedanovic I need to pass the access token just like in your example, AND use the websockets protocol... can you please elaborate how you solved it? From your example above, its not clear if you ultimately got it working WITH the query string or not?

**Comment by tmedanovic** [comment]
@pranavmehta 

I did it using headers from:
https://github.com/SignalR/java-client/pull/64/files

It boils down to this line, so headers from connection are passed:
```java
 post.setHeaders(connection.getHeaders());
```

Then after you create HubConnection object connection:

```java
  // Setup authorization headers
        connection.getHeaders().put("Authorization", "Bearer " + TokenInterceptor.getInstance().getToken());
```

Hope that helps.

**Comment by rod82** [comment]
Just to add my experience with this problem, adding the URI transformation code to replace 'https://' with 'wss://' in combination with the SSL code pasted by e82eric worked for me (below for reference) in the `WebsocketTransport` class worked for me.

    SSLSocketFactory factory = (SSLSocketFactory) SSLSocketFactory.getDefault();

    try {
        mWebSocketClient.setSocket(factory.createSocket());
    } catch (IOException e1) {
        // TODO Auto-generated catch block
        e1.printStackTrace();
    }

    mWebSocketClient.connect();

**Comment by pranavmehta** [comment]
I was able to get it to work with a querystring.... I basically applied patch 64 linked above. In my case, I am passing the access token via a query string parameter.

**Comment by rod82** [comment]
I completely missed the patch linked. Just applied it and also solved an issue I was having with sending authentication headers. Excellent!

**Comment by nickfurnesschubb** [comment]
I have applied patch 64 but still unable to connect using WebSockets. I have the following code:

//SignalRFuture<Void> awaitConnection = connection.start(new ServerSentEventsTransport(connection.getLogger()));
 SignalRFuture<Void> awaitConnection = connection.start(new WebsocketTransport(connection.getLogger()));
            //SignalRFuture<Void> awaitConnection = connection.start(new LongPollingTransport(connection.getLogger()));

I can comment out the linf for WebSockets and uncomment either line for long polling or SSE and everything starts to work, I see my .NET SignalR server on another machine receiving requests and outputting debug messages.

From what i can tell the .connect() function when using WebSockets doesn't complete or return the connected state so the onOpen() code is never run.
From the machine i am developing with Android I have a .NET test client that connects to the server fine.

Any pointers would be great.

I tried the WebSocketImpl.DEBUG = true to get more debug info but it doesn't seem to output anymore.

Given long enough (say 20/30 seconds) the connection attempt does timeout.
I am using web socket 1.3.1 as advised and using the latest master version of code plus the patch in #64

**Comment by nickfurnesschubb** [comment]
The reason it wasn't working for me was because the SignalR server itself was not hosted on a Womdows 8 or above with IIS 8 which enables you to add the WebSocket feature (well enable it). A little frustrating given the time spent troubleshooting ... apparently web browsers have their own support for web sockets and i assume .NET must do as well but when is comes the a native app on android then your server has to have the ability. 

If there are any alternatives then that would be great as i may not be able to upgrade the OS ...

**Comment by mirjalal** [comment]
@RVoiseyFirstApp have you solved your problem?

**Comment by nickfurnesschubb** [comment]
Yes, kinda ... You can force the transport type used if you are not able to have a windows version with IIS 8 on it. It should be clever enough to know and detect this but if you explicitly set the transport type yourself to use ServerSentEvents then it should work. Then maybe have something in your system to make this configurable yourself if/when you have the environment that supports web sockets.

code:
SignalRFuture awaitConnection = connection.start(new ServerSentEventsTransport(connection.getLogger()));

**Comment by mirjalal** [comment]
Oh, that's good news today for me...
But I'm getting these errors. I understand that client couldn't find the my computer's IP address on the network. I have connected all devices to same home WiFi network.

12-11 22:26:06.688 21052-21117/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Creating hub proxy: chathub
12-11 22:26:06.688 21052-21117/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Entered startLock in start
12-11 22:26:06.688 21052-21117/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Start the connection, using serverSentEvents transport
12-11 22:26:06.688 21052-21117/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Start negotiation
12-11 22:26:06.688 21052-21117/autodrome.client E/LOGGER MESSAGE: message: serverSentEvents - Start the negotiation with the server
12-11 22:26:06.698 21052-21117/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Getting connection data: [{"name":"chathub"}]
12-11 22:26:06.698 21052-21117/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Getting connection data: [{"name":"chathub"}]
12-11 22:26:06.698 21052-21117/autodrome.client E/LOGGER MESSAGE: message: serverSentEvents - Execute the request
12-11 22:26:06.708 21052-21117/autodrome.client E/LOGGER MESSAGE: message: Create new thread for HTTP Connection
12-11 22:26:06.708 21052-21118/autodrome.client E/LOGGER MESSAGE: message: Execute the HTTP Request
12-11 22:26:06.708 21052-21118/autodrome.client E/LOGGER MESSAGE: message: URL: http://myIpAddress:8080/signalr/negotiate?clientProtocol=1.3&connectionData=%5B%7B%22name%22%3A%22chathub%22%7D%5D&
12-11 22:26:06.708 21052-21118/autodrome.client E/LOGGER MESSAGE: message: VERB: GET
12-11 22:26:06.708 21052-21118/autodrome.client E/LOGGER MESSAGE: message: Header User-Agent: SignalR (lang=Java; os=android; version=2.0)
12-11 22:26:06.708 21052-21118/autodrome.client E/LOGGER MESSAGE: message: CONTENT: null
12-11 22:26:06.708 21052-21052/autodrome.client I/brcm-gr: [gralloc_lock]: new usage 0x933
12-11 22:26:06.718 21052-21118/autodrome.client E/LOGGER MESSAGE: message: Request executed
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: Error executing request: failed to connect to /myIpAddress (port 8080) after 15000ms
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Error: java.net.SocketTimeoutException: failed to connect to /myIpAddress (port 8080) after 15000ms
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Triggering disconnect
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Entered stateLock in disconnect
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Disconnecting
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Stopping the connection
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Cancelling abort
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Clearing invocation callbacks: Connection closed
12-11 22:26:36.817 21052-21335/autodrome.client A/ERROR: failed to connect to /myIpAddress (port 8080) after 15000ms
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Error: java.net.SocketTimeoutException: failed to connect to /myIpAddress (port 8080) after 15000ms
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Triggering disconnect
12-11 22:26:36.817 21052-21335/autodrome.client E/LOGGER MESSAGE: message: HubConnection - Entered stateLock in disconnect
12-11 22:26:36.817 21052-21335/autodrome.client A/ERROR: failed to connect to /myIpAddress (port 8080) after 15000ms


but how to solve this problem? Could you help me please? :confused:  I'm new to this library.

Thanks very much.

**Comment by mirjalal** [comment]
I solved my problem. I didn't added new rule for the specific port on my firewall. 
Now everything working. Thanks :feelsgood:

**Comment by MisaelM293** [comment]
Solved this problem see the following link.

http://stackoverflow.com/questions/37976504/signal-r-native-with-websocket-in-android-app

**Comment by aspnet-hello** [comment]
All issues in this repo are being closed because this repo is no longer in use. Please see the readme for more information: https://github.com/SignalR/java-client/blob/master/readme.md.
